define({
  "attributes": {
    "date": "Date updated",
    "crdate": "Date created",
    "user": "updated from",
    "cruser": "created from",
    "lat": "Latitude",
    "lng": "Longitude",
    "published": "published",
  },
  "langCode": "de",
  "development": "Entwicklung",
  "backend_development": "Backend im Entwicklungsmodus",
  "frontend_development": "Frontend im Entwicklungsmodus",
  "cancel": "Abbrechen",
  "closeit": "Schließen",
  "deleteModel": "Löschen",
  "navigation": "Allgemein",
  "save": "Speichern",
  "savenew": "Speichern & Neu",
  "saveclose": "Speicher & Schließen",
  "date": "Datum",
  "publish": "Veröffentlichen",
  "unpublish": "Unveröffentlichen",
  "dateformat": "%d.%m.%y %H:%m:%S",
  "sunday": "Sonntag",
  "monday": "Montag",
  "tuesday": "Dienstag",
  "wednesday": "Mittwoch",
  "thursday": "Donnerstag",
  "friday": "Freitag",
  "saturday": "Samstag",
  "january": "Jänner",
  "february": "Februar",
  "march": "März",
  "april": "April",
  "may": "Mai",
  "june": "Juni",
  "july": "July",
  "august": "August",
  "september": "September",
  "october": "Oktober",
  "november": "November",
  "december": "Dezember"
});
