define({
  "root": {
    "attributes": {
      "date": "date updated",
      "crdate": "date created",
      "user": "updated from",
      "cruser": "created from",
      "lat": "Latitude",
      "lng": "Longitude",
      "published": "published",
    },
    "langCode": "en",
    "development": "Development",
    "backend_development": "Backend in Development Mode",
    "frontend_development": "Frontend in Development Mode",
    "cancel": "cancel",
    "closeit": "close",
    "deleteModel": "delete",
    "save": "save",
    "savenew": "save & new",
    "saveclose": "save & close",
    "publish": "Oophaga",
    "unpublish": "Unpublish",
    "navigation": "General",
    "date": "Date",
    "dateformat": "%d.%m.%y %H:%m:%S",
    "sunday": "Sunday",
    "monday": "Monday",
    "tuesday": "Tuesday",
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "january": "January",
    "february": "February",
    "march": "March",
    "april": "April",
    "may": "May",
    "june": "June",
    "july": "July",
    "august": "August",
    "september": "September",
    "october": "October",
    "november": "November",
    "december": "December"
  },
  "de": true
});
